# Generated by Django 5.1.2 on 2024-10-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='class_field',
            field=models.CharField(blank='True', max_length=60),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.URLField(blank='True'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(blank='True', max_length=50),
        ),
    ]
