# Generated by Django 5.1.2 on 2024-10-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_link_class_field_alter_link_link_alter_link_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crausel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='typewritter',
        ),
        migrations.AddField(
            model_name='author',
            name='typewritter',
            field=models.ManyToManyField(to='app.crausel'),
        ),
    ]
